# Generated by Django 3.2.4 on 2022-01-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('matters', models.CharField(blank=True, max_length=100)),
                ('not_mischief', models.BooleanField(default=False)),
                ('article_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.article_form')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
