# Generated by Django 2.2.5 on 2021-12-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_form',
            name='author',
        ),
    ]
