# Generated by Django 2.2.5 on 2021-12-23 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(default=' ', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article_form',
            name='number',
        ),
        migrations.AddField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 18, 6, 9, 664581)),
        ),
    ]
