# Generated by Django 3.2.4 on 2022-02-28 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 35, 13, 426802)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 35, 13, 426802)),
        ),
    ]
