# Generated by Django 2.2.5 on 2021-12-23 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211223_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 18, 27, 44, 496729)),
        ),
    ]
