# Generated by Django 3.2.4 on 2022-02-28 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220228_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 40, 18, 833674)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 22, 40, 18, 833674)),
        ),
    ]
