# Generated by Django 3.2.4 on 2022-01-19 16:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220119_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeInfoThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 19, 16, 59, 9, 722605, tzinfo=utc))),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeInfoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 1, 19, 16, 59, 9, 722605, tzinfo=utc))),
                ('about', models.CharField(max_length=140)),
                ('thread', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.exchangeinfothread')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
