# Generated by Django 2.2.5 on 2021-12-25 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211223_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 15, 46, 45, 540409)),
        ),
    ]
