# Generated by Django 3.2.4 on 2022-01-20 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exchangeinfomodel_exchangeinfothread'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeinfothread',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangeinfomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 11, 12, 53, 345086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exchangeinfomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangeinfothread',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 11, 12, 53, 345086, tzinfo=utc)),
        ),
    ]
