# Generated by Django 3.2.4 on 2022-03-01 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220228_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-last_login'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='character',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, upload_to='user_icon/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='playfield',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ply_f'),
        ),
        migrations.AlterField(
            model_name='threadcomments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 2, 40, 6, 303243)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 2, 40, 6, 303243)),
        ),
    ]
