# Generated by Django 2.2.5 on 2021-12-25 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211225_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 16, 21, 35, 711972)),
        ),
    ]
