# Generated by Django 3.2.10 on 2022-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220108_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_form',
            name='author',
        ),
        migrations.AddField(
            model_name='customuser',
            name='character',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comments',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
