# Generated by Django 3.2.10 on 2022-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220108_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='comments',
            field=models.CharField(blank=True, default='自己紹介はありません', max_length=300),
        ),
    ]
