# Generated by Django 2.2.5 on 2021-12-25 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211225_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_form',
            name='num',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_form',
            name='per',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_form',
            name='rnk',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 20, 3, 41, 638534)),
        ),
    ]
