# Generated by Django 2.2.5 on 2021-12-26 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211225_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 17, 52, 3, 163480)),
        ),
    ]
