# Generated by Django 3.2.4 on 2022-01-20 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220120_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='about',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeinfomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 12, 39, 16, 137822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 12, 39, 16, 136821, tzinfo=utc)),
        ),
    ]
