# Generated by Django 2.2.5 on 2021-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211226_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_form',
            old_name='rnk',
            new_name='rnk_max',
        ),
        migrations.RemoveField(
            model_name='article_form',
            name='date',
        ),
        migrations.AddField(
            model_name='article_form',
            name='rnk_min',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
