# Generated by Django 2.2.5 on 2021-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211226_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AddField(
            model_name='article_form',
            name='hard',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
