# Generated by Django 2.2.5 on 2021-12-26 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211226_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
