# Generated by Django 2.2.5 on 2021-12-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211226_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_form',
            name='hard',
            field=models.TextField(),
        ),
    ]
