# Generated by Django 3.2.4 on 2022-01-21 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220121_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='update',
        ),
        migrations.AlterField(
            model_name='exchangeinfomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 23, 42, 956130, tzinfo=utc)),
        ),
    ]
