# Generated by Django 3.2.4 on 2022-01-21 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220121_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 25, 23, 869128, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='thread',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangeinfomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 25, 23, 869128, tzinfo=utc)),
        ),
    ]
