# Generated by Django 2.2.5 on 2021-12-27 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211227_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 1, 3, 3, 441658)),
        ),
        migrations.AlterField(
            model_name='article_form',
            name='hard',
            field=models.CharField(max_length=100),
        ),
    ]
