# Generated by Django 3.2.4 on 2022-01-21 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newsmodel_uuidtaggeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 9, 27, 50, 35339, tzinfo=utc)),
        ),
    ]
