# Generated by Django 3.2.4 on 2022-01-21 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 9, 31, 51, 556722, tzinfo=utc)),
        ),
    ]
